# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\"&\n\x05\x45ntry\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\"b\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0b\x63\x61ndidateId\x18\x02 \x01(\x05\x12\x14\n\x0clastLogIndex\x18\x03 \x01(\x05\x12\x13\n\x0blastLogTerm\x18\x04 \x01(\x05\"O\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x13\n\x0bvoteGranted\x18\x02 \x01(\x08\x12\x15\n\rleaseDuration\x18\x03 \x01(\x01\"\x98\x01\n\nLogRequest\x12\x10\n\x08leaderId\x18\x01 \x01(\x05\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x11\n\tprefixLen\x18\x03 \x01(\x05\x12\x12\n\nprefixTerm\x18\x04 \x01(\x05\x12\x14\n\x0cleaderCommit\x18\x05 \x01(\x05\x12\x16\n\x06suffix\x18\x06 \x03(\x0b\x32\x06.Entry\x12\x15\n\rleaseInterval\x18\x07 \x01(\x05\"K\n\x0bLogResponse\x12\x10\n\x08\x66ollower\x18\x01 \x01(\x05\x12\x0c\n\x04term\x18\x02 \x01(\x05\x12\x0b\n\x03\x61\x63k\x18\x03 \x01(\x05\x12\x0f\n\x07success\x18\x04 \x01(\x08\"\"\n\x0fServeClientArgs\x12\x0f\n\x07Request\x18\x01 \x01(\t\"C\n\x10ServeClientReply\x12\x0c\n\x04\x44\x61ta\x18\x01 \x01(\t\x12\x10\n\x08LeaderID\x18\x02 \x01(\x05\x12\x0f\n\x07Success\x18\x03 \x01(\x08\x32\xa3\x01\n\x04Raft\x12:\n\x0bRequestVote\x12\x13.RequestVoteRequest\x1a\x14.RequestVoteResponse\"\x00\x12)\n\nProcessLog\x12\x0b.LogRequest\x1a\x0c.LogResponse\"\x00\x12\x34\n\x0bServeClient\x12\x10.ServeClientArgs\x1a\x11.ServeClientReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ENTRY']._serialized_start=14
  _globals['_ENTRY']._serialized_end=52
  _globals['_REQUESTVOTEREQUEST']._serialized_start=54
  _globals['_REQUESTVOTEREQUEST']._serialized_end=152
  _globals['_REQUESTVOTERESPONSE']._serialized_start=154
  _globals['_REQUESTVOTERESPONSE']._serialized_end=233
  _globals['_LOGREQUEST']._serialized_start=236
  _globals['_LOGREQUEST']._serialized_end=388
  _globals['_LOGRESPONSE']._serialized_start=390
  _globals['_LOGRESPONSE']._serialized_end=465
  _globals['_SERVECLIENTARGS']._serialized_start=467
  _globals['_SERVECLIENTARGS']._serialized_end=501
  _globals['_SERVECLIENTREPLY']._serialized_start=503
  _globals['_SERVECLIENTREPLY']._serialized_end=570
  _globals['_RAFT']._serialized_start=573
  _globals['_RAFT']._serialized_end=736
# @@protoc_insertion_point(module_scope)
